import { useEffect, useRef, useState } from 'react';
import { ArchiveRestore, Download, FileSpreadsheet, Upload, Users } from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { useToast } from '@/components/ui/Toast';
import { Modal } from '@/components/ui/Modal';
import type { ClassRoom, Student } from '@/types';
import { blankStudentTemplate, downloadFile, parseCsv, previewStudentCsvImport, studentsWithClassToCsv, type StudentCsvImportPreview } from '@/utils/csv';
import { backupSummary, makeFullBackup, type FullBackup, validateFullBackup } from '@/utils/backup';

export function ImportExport() {
  const { repo, mode } = useApp(); const { toast } = useToast();
  const [classes, setClasses] = useState<ClassRoom[]>([]); const [students, setStudents] = useState<Student[]>([]); const [preview, setPreview] = useState<StudentCsvImportPreview | null>(null); const [backup, setBackup] = useState<FullBackup | null>(null); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState('');
  const csvRef = useRef<HTMLInputElement>(null); const jsonRef = useRef<HTMLInputElement>(null);
  const load = async () => { if (!repo) return; const [c, s] = await Promise.all([repo.getClasses(), repo.getStudents()]); setClasses(c); setStudents(s); };
  useEffect(() => { void load(); }, [repo]);
  const selectCsv = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; try { setPreview(previewStudentCsvImport(parseCsv(await file.text()), classes, students)); } catch { toast('Could not read this CSV file', 'error'); } finally { if (csvRef.current) csvRef.current.value = ''; } };
  const confirmCsv = async () => { if (!repo || !preview || preview.invalid.length || preview.classes.some(c => c.status === 'ambiguous')) return toast('Resolve invalid or ambiguous rows before importing.', 'error'); setBusy(true); try { const ids = new Map<string, string>(); for (const c of preview.classes) ids.set(c.key, c.status === 'existing' && c.classId ? c.classId : (await repo.createClass({ name: c.name, division: c.division, academicYear: c.academicYear })).id); let count = 0; for (const item of preview.students) { if (item.status === 'unchanged') continue; const classId = ids.get(item.classKey); if (!classId) throw new Error('Class resolution failed'); const value = { classId, rollNumber: item.rollNumber, name: item.name, ...(item.admissionNumber ? { admissionNumber: item.admissionNumber } : {}) }; if (item.status === 'update' && item.existing) await repo.updateStudent({ ...item.existing, ...value }); else await repo.createStudent(value); count++; } await load(); setPreview(null); toast(`Imported ${count} student${count === 1 ? '' : 's'}.`, 'success'); } catch (e: any) { toast(e.message || 'Import failed.', 'error'); } finally { setBusy(false); } };
  const exportFull = async () => { if (!repo) return; try { downloadFile(JSON.stringify(makeFullBackup(await repo.exportBackup()), null, 2), `students-academics-manager-backup-${new Date().toISOString().slice(0, 10)}.json`, 'application/json'); toast('Full backup downloaded.', 'success'); } catch { toast('Could not export backup.', 'error'); } };
  const selectBackup = async (e: React.ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; try { setBackup(validateFullBackup(JSON.parse(await file.text()))); } catch (error: any) { toast(error.message || 'Invalid JSON backup. No data was changed.', 'error'); } finally { if (jsonRef.current) jsonRef.current.value = ''; } };
  const restore = async () => { if (!repo || !backup) return; setBusy(true); try { await repo.importBackup(backup.data, (done, total) => setProgress(`Restoring ${done} / ${total} records`)); await load(); setBackup(null); toast('Full backup restored in the current mode.', 'success'); } catch (error: any) { toast(error.message || 'Restore failed; some records may not have been restored.', 'error'); } finally { setBusy(false); setProgress(''); } };
  return <div className="space-y-6 max-w-3xl"><h1 className="text-2xl font-bold">Import / Export</h1>
    <div className="card p-6"><div className="flex items-center gap-2 mb-3"><Upload className="w-5 h-5 text-primary-600" /><h2 className="font-semibold">Import Students</h2></div><p className="text-sm text-gray-500 mb-4">Import a CSV to add or update students and safely reuse matching classes.</p><div className="flex gap-2 flex-wrap"><button className="btn-primary" onClick={() => csvRef.current?.click()}><Upload className="w-4 h-4" />Import Students</button><button className="btn-secondary" onClick={() => downloadFile(blankStudentTemplate(), 'student_import_template.csv')}><FileSpreadsheet className="w-4 h-4" />Download Blank Template</button><input ref={csvRef} type="file" accept=".csv,text/csv" className="hidden" onChange={selectCsv} /></div><p className="text-xs text-gray-400 mt-3">Works in {mode === 'online' ? 'Online Mode (your Firebase account only)' : 'Offline Mode (this device only)'}.</p></div>
    <div className="card p-6"><div className="flex items-center gap-2 mb-3"><Users className="w-5 h-5 text-primary-600" /><h2 className="font-semibold">Student CSV Export</h2></div>{classes.length === 0 ? <p className="text-sm text-gray-500">No classes to export yet.</p> : classes.map(c => <div className="flex justify-between py-2 border-b" key={c.id}><span>{c.name} {c.division} · {c.academicYear}</span><button className="btn-ghost text-sm" onClick={() => { const scoped = students.filter(s => s.classId === c.id); if (!scoped.length) return toast('No students to export', 'info'); downloadFile(studentsWithClassToCsv(scoped, c), `${c.name}_students.csv`); }}><Download className="w-4 h-4" />Export</button></div>)}</div>
    <div className="card p-6"><div className="flex items-center gap-2 mb-3"><ArchiveRestore className="w-5 h-5 text-primary-600" /><h2 className="font-semibold">Full Backup</h2></div><p className="text-sm text-gray-500 mb-4">Exports all academic records and relationships for {mode === 'online' ? 'your current online account' : 'this device only'}. Restore replaces data only in this same mode.</p><div className="flex gap-2 flex-wrap"><button className="btn-secondary" onClick={() => void exportFull()}><Download className="w-4 h-4" />Export Full Backup (.json)</button><button className="btn-primary" onClick={() => jsonRef.current?.click()}><Upload className="w-4 h-4" />Import Full Backup (.json)</button><input ref={jsonRef} type="file" accept=".json,application/json" className="hidden" onChange={selectBackup} /></div></div>
    <Modal open={!!preview} onClose={() => !busy && setPreview(null)} title="Student Import Preview" size="lg" footer={<><button className="btn-secondary" onClick={() => setPreview(null)} disabled={busy}>Cancel</button><button className="btn-primary" onClick={() => void confirmCsv()} disabled={busy || !!preview?.invalid.length}>{busy ? 'Importing...' : 'Confirm Import'}</button></>}>{preview && <div className="space-y-3 text-sm"><p>Classes to create: {preview.classes.filter(c => c.status === 'create').length} · Existing classes: {preview.classes.filter(c => c.status === 'existing').length}</p><p>New students: {preview.students.filter(s => s.status === 'create').length} · Updates: {preview.students.filter(s => s.status === 'update').length}</p>{preview.invalid.map((x, i) => <p className="text-error-600" key={i}>{x.reason}</p>)}</div>}</Modal>
    <Modal open={!!backup} onClose={() => !busy && setBackup(null)} title="Restore Full Backup" footer={<><button className="btn-secondary" onClick={() => setBackup(null)} disabled={busy}>Cancel</button><button className="btn-primary" onClick={() => void restore()} disabled={busy}>{busy ? 'Restoring...' : 'Restore and Replace Data'}</button></>}>{backup && <div className="space-y-3 text-sm"><p className="font-semibold">Restore this backup?</p><p>Existing data in the current mode will be replaced by the contents of this backup. Offline and Online data are separate; this affects only the current mode.</p><p>Format: {backup.format}<br />Schema: {backup.schemaVersion} · App: {backup.appVersion}<br />Exported: {new Date(backup.exportedAt).toLocaleString()}</p><p>Classes: {backupSummary(backup).classes} · Students: {backupSummary(backup).students} · Exams: {backupSummary(backup).exams} · Assignments: {backupSummary(backup).assignments} · Marks: {backupSummary(backup).marks} · Statuses: {backupSummary(backup).statuses} · Grace marks: {backupSummary(backup).graceMarks} · Analyses: {backupSummary(backup).analyses}</p>{progress && <p>{progress}</p>}</div>}</Modal>
  </div>;
}
