import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Line, LineChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { FileBarChart, Printer } from 'lucide-react';
import { useApp } from '@/context/AppContext';
import { EmptyState } from '@/components/ui/EmptyState';
import type { Assignment, AssignmentStatus, ClassRoom, CombinedAnalysis, Exam, ExamMark, GraceMark, PlusOneMark, Student, UserSettings } from '@/types';
import { calcCombinedPercentage, calcPercentage, calcPlusOneResult, formatNumber, formatPercent } from '@/utils/calculations';

const fallback: Pick<UserSettings, 'plusOneMaxTE'|'plusOneMaxCE'|'plusOneMaxTotal'|'requiredTEPercent'|'requiredTotalPercent'|'doublePassRequiredPercent'|'doublePassEnabled'|'aPlusThreshold'> = { plusOneMaxTE: 80, plusOneMaxCE: 20, plusOneMaxTotal: 100, requiredTEPercent: 30, requiredTotalPercent: 30, doublePassRequiredPercent: 30, doublePassEnabled: true, aPlusThreshold: 90 };
type ReportType = 'student' | 'class'; type Direction = 'asc'|'desc';
const rollCompare = (a: string, b: string) => a.localeCompare(b, undefined, { numeric: true });

export function Reports() {
  const { repo } = useApp(); const [classes,setClasses]=useState<ClassRoom[]>([]); const [students,setStudents]=useState<Student[]>([]); const [exams,setExams]=useState<Exam[]>([]); const [settings,setSettings]=useState<UserSettings|null>(null);
  const [combined,setCombined]=useState<CombinedAnalysis[]>([]); const [marks,setMarks]=useState<ExamMark[]>([]); const [plus,setPlus]=useState<PlusOneMark[]>([]); const [assignments,setAssignments]=useState<Assignment[]>([]); const [statuses,setStatuses]=useState<AssignmentStatus[]>([]); const [grace,setGrace]=useState<GraceMark[]>([]);
  const [type,setType]=useState<ReportType>('student'); const [classId,setClassId]=useState(''); const [studentId,setStudentId]=useState('');
  useEffect(()=>{ if(!repo)return; void Promise.all([repo.getClasses(),repo.getStudents(),repo.getExams(),repo.getSettings()]).then(([c,s,e,x])=>{setClasses(c);setStudents(s);setExams(e);setSettings(x);}); },[repo]);
  useEffect(()=>{ if(!repo||!classId)return; void Promise.all([repo.getCombinedAnalyses(classId),repo.getAllMarksForClass(classId),repo.getAllPlusOneMarksForClass(classId),repo.getAssignments(classId),repo.getAllAssignmentStatusesForClass(classId),repo.getGraceMarks(classId)]).then(([c,m,p,a,st,g])=>{setCombined(c);setMarks(m);setPlus(p);setAssignments(a);setStatuses(st);setGrace(g);}); },[repo,classId]);
  const classStudents=students.filter(s=>s.classId===classId).sort((a,b)=>rollCompare(a.rollNumber,b.rollNumber)); const classExams=exams.filter(e=>e.classId===classId);
  if(!classes.length) return <EmptyState title="No data for reports" description="Create a class first." action={<Link to="/classes" className="btn-primary">Go to Classes</Link>}/>;
  return <div className="space-y-6"><div className="flex justify-between"><h1 className="text-2xl font-bold">Reports</h1>{classId&&<button className="btn-primary" onClick={()=>window.print()}><Printer className="w-4 h-4"/> Print / Save PDF</button>}</div><div className="card p-5 space-y-4 no-print"><div className="flex gap-2"><button className={`btn flex-1 ${type==='student'?'btn-primary':'btn-secondary'}`} onClick={()=>setType('student')}>Student Report</button><button className={`btn flex-1 ${type==='class'?'btn-primary':'btn-secondary'}`} onClick={()=>setType('class')}>Class Report</button></div><div className="grid md:grid-cols-2 gap-3"><div><label className="label">Class</label><select className="input" value={classId} onChange={e=>{setClassId(e.target.value);setStudentId('')}}><option value="">Choose a class...</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} {c.division} ({c.academicYear})</option>)}</select></div>{type==='student'&&<div><label className="label">Student</label><select className="input" value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Choose a student...</option>{classStudents.map(s=><option key={s.id} value={s.id}>{s.rollNumber} — {s.name}</option>)}</select></div>}</div></div>{type==='student'&&classId&&studentId&&<StudentReport student={classStudents.find(s=>s.id===studentId)!} exams={classExams} marks={marks} plus={plus} combined={combined} settings={settings}/>} {type==='class'&&classId&&<ClassReport students={classStudents} exams={classExams} marks={marks} plus={plus} combined={combined} assignments={assignments} statuses={statuses} grace={grace} settings={settings}/>}</div>;
}

function StudentReport({student,exams,marks,plus,combined,settings}:{student:Student;exams:Exam[];marks:ExamMark[];plus:PlusOneMark[];combined:CombinedAnalysis[];settings:UserSettings|null}) {
  const config=settings??fallback; const dec=settings?.decimalPlaces??2;
  const data=[...exams.map(ex=>{const mark=marks.find(m=>m.examId===ex.id&&m.studentId===student.id); const p=ex.type==='plusOne'?calcPlusOneResult(plus.find(m=>m.examId===ex.id&&m.studentId===student.id)?.teMarks??null,plus.find(m=>m.examId===ex.id&&m.studentId===student.id)?.ceMarks??null,config).percentage:calcPercentage(mark?.marks??null,ex.maxMarks);return {id:ex.id,title:ex.name,date:ex.date,percentage:p,type:ex.type};}).filter(x=>x.percentage!==null&&x.date),].sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id)).map(x=>({name:x.title,percentage:x.percentage}));
  return <div className="space-y-6 print-area"><div className="card p-6"><h2 className="text-xl font-bold">{student.name}</h2><p className="text-sm text-gray-500">Roll No: {student.rollNumber}{student.admissionNumber&&` · Admission No: ${student.admissionNumber}`}</p></div><div className="card p-6"><h3 className="font-semibold mb-3">Exam Performance</h3>{exams.sort((a,b)=>(a.date||'').localeCompare(b.date||'')).map(ex=>{const normal=marks.find(m=>m.examId===ex.id&&m.studentId===student.id);const r=ex.type==='plusOne'?calcPlusOneResult(plus.find(m=>m.examId===ex.id&&m.studentId===student.id)?.teMarks??null,plus.find(m=>m.examId===ex.id&&m.studentId===student.id)?.ceMarks??null,config):null;return <div key={ex.id} className="flex justify-between py-2 border-b"><span>{ex.name}{!ex.date&&<small className="ml-2 text-amber-600">Date missing</small>}</span><span>{r?`CE: ${r.ceMarks??'—'} · TE: ${r.teMarks??'—'} · Total: ${r.total??'—'} · ${r.percentage===null?'—':formatPercent(r.percentage,dec)}`:`${normal?.marks??'—'} / ${ex.maxMarks}`}</span></div>})}</div>{combined.length>0&&<div className="card p-6"><h3 className="font-semibold mb-3">Combined Analyses</h3>{combined.map(c=>{const r=calcCombinedPercentage(exams.filter(e=>c.examIds.includes(e.id)).map(e=>({obtained:marks.find(m=>m.examId===e.id&&m.studentId===student.id)?.marks??null,maxMarks:e.maxMarks})));return <p key={c.id}>{c.name}: {r.combinedObtained}/{r.combinedMax} ({r.combinedPercentage===null?'—':formatPercent(r.combinedPercentage,dec)})</p>})}</div>}{data.length>0&&<div className="card p-6 no-print"><h3 className="font-semibold mb-4">Percentage Trend</h3><ResponsiveContainer width="100%" height={250}><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip formatter={v=>formatPercent(Number(v),dec)}/><Line type="monotone" dataKey="percentage" stroke="#3a8b96"/></LineChart></ResponsiveContainer></div>}</div>;
}

function ClassReport({students,exams,marks,plus,combined,assignments,statuses,grace,settings}:{students:Student[];exams:Exam[];marks:ExamMark[];plus:PlusOneMark[];combined:CombinedAnalysis[];assignments:Assignment[];statuses:AssignmentStatus[];grace:GraceMark[];settings:UserSettings|null}) {
 const [sort,setSort]=useState('roll');const [dir,setDir]=useState<Direction>('asc');const [query,setQuery]=useState('');const [result,setResult]=useState('all');const [assignment,setAssignment]=useState('all');const [threshold,setThreshold]=useState('');const config=settings??fallback;const dec=settings?.decimalPlaces??2; const regular=exams.filter(e=>e.type==='regular'); const plusOne=exams.filter(e=>e.type==='plusOne');
 const rows=useMemo(()=>students.map(student=>{const po=plusOne[0]?calcPlusOneResult(plus.find(m=>m.examId===plusOne[0].id&&m.studentId===student.id)?.teMarks??null,plus.find(m=>m.examId===plusOne[0].id&&m.studentId===student.id)?.ceMarks??null,config):null;const examValues=Object.fromEntries(regular.map(e=>[e.id,marks.find(m=>m.examId===e.id&&m.studentId===student.id)?.marks??null]));const combinedValues=Object.fromEntries(combined.map(c=>[c.id,calcCombinedPercentage(regular.filter(e=>c.examIds.includes(e.id)).map(e=>({obtained:examValues[e.id]??null,maxMarks:e.maxMarks})))]));const submitted=statuses.filter(s=>s.studentId===student.id&&s.submitted).length;return {student,po,examValues,combinedValues,submitted,totalAssignments:assignments.length,grace:grace.filter(g=>g.studentId===student.id).reduce((x,g)=>x+g.marks,0)};}),[students,plusOne,plus,config,regular,marks,combined,statuses,assignments.length,grace]);
 const column=(key:string,label:string)=><th key={key} className="px-3 py-3 text-left text-xs uppercase cursor-pointer whitespace-nowrap" onClick={()=>{if(sort===key)setDir(dir==='asc'?'desc':'asc');else{setSort(key);setDir('asc')}}}>{label} {sort===key&&(dir==='asc'?'↑':'↓')}</th>;
 const shown=rows.filter(r=>{const q=query.toLowerCase();const matches=!q||r.student.name.toLowerCase().includes(q)||r.student.rollNumber.includes(q)||(r.student.admissionNumber||'').toLowerCase().includes(q);const p=r.po;const outcome=result==='all'||(result==='passed'&&p?.passed)||(result==='failed'&&p&&!p.passed)||(result==='double'&&p?.doublePass)||(result==='not-double'&&p&&!p.doublePass)||(result==='aplus'&&p?.aPlusAchieved)||(result==='below'&&p?.tePercentage!==null&&p!.tePercentage<Number(threshold))||(result==='above'&&p?.tePercentage!==null&&p!.tePercentage>Number(threshold));const work=assignment==='all'||(assignment==='complete'&&r.totalAssignments>0&&r.submitted===r.totalAssignments)||(assignment==='incomplete'&&r.submitted<r.totalAssignments);return matches&&outcome&&work;}).sort((a,b)=>{const val=(r:any)=>sort==='roll'?r.student.rollNumber:sort==='name'?r.student.name:sort==='plus'?r.po?.tePercentage??-1:sort==='assign'?r.submitted:sort==='grace'?r.grace:sort.startsWith('combined:')?r.combinedValues[sort.slice(9)]?.combinedPercentage??-1:r.examValues[sort]??-1;const av=val(a),bv=val(b);const c=typeof av==='string'? (sort==='roll'?rollCompare(av,bv):av.localeCompare(bv)):av-bv;return dir==='asc'?c:-c;});
 const plusMetric=(value:number|null|undefined, complete:boolean, achieved:boolean)=>!complete?<span className="chip bg-gray-100 dark:bg-gray-800 text-gray-500">Incomplete</span>:<span className={`chip ${achieved?'bg-success-100 dark:bg-success-900/30 text-success-700 dark:text-success-300':'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300'}`}>{value===0?'0':formatNumber(value??0,dec)}</span>;
 return <div className="space-y-4 print-area"><div className="card p-5 no-print grid md:grid-cols-5 gap-3"><input className="input" placeholder="Search student, roll, admission..." value={query} onChange={e=>setQuery(e.target.value)}/><select className="input" value={result} onChange={e=>setResult(e.target.value)}><option value="all">All results</option><option value="passed">Passed</option><option value="failed">Failed</option><option value="double">Double Pass</option><option value="not-double">Not Double Pass</option><option value="aplus">A+</option><option value="below">Below TE percentage</option><option value="above">Above TE percentage</option></select><input className="input" type="number" placeholder="TE percentage filter" value={threshold} onChange={e=>setThreshold(e.target.value)}/><select className="input" value={assignment} onChange={e=>setAssignment(e.target.value)}><option value="all">All assignments</option><option value="complete">Complete</option><option value="incomplete">Incomplete</option></select><button className="btn-secondary" onClick={()=>{setQuery('');setResult('all');setAssignment('all');setThreshold('');setSort('roll');setDir('asc')}}>Clear Filters</button></div><div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-gray-50 dark:bg-gray-800/50">{column('roll','Roll')}{column('name','Student')}{plusOne.length>0&&<>{column('plus','Plus One TE %')}<th className="px-3 py-3 text-left text-xs uppercase whitespace-nowrap">Double Pass Required</th><th className="px-3 py-3 text-left text-xs uppercase whitespace-nowrap">Full A+ Required</th></>}{regular.map(e=>column(e.id,e.name))}{combined.map(c=>column(`combined:${c.id}`,c.name))}{column('assign','Assignments')}{column('grace','Grace')}</tr></thead><tbody>{shown.map(r=><tr key={r.student.id} className="border-t"><td className="px-3 py-2">{r.student.rollNumber}</td><td className="px-3 py-2">{r.student.name}</td>{plusOne.length>0&&<><td className="px-3 py-2">{!r.po||r.po.isIncomplete?<span className="chip bg-gray-100 dark:bg-gray-800 text-gray-500">Incomplete</span>:formatPercent(r.po.tePercentage!,dec)}</td><td className="px-3 py-2">{plusMetric(r.po?.marksRequiredForDoublePass,!r.po?.isIncomplete,!!r.po?.doublePass)}</td><td className="px-3 py-2">{plusMetric(r.po?.marksRequiredForAPlus,!r.po?.isIncomplete,!!r.po?.aPlusAchieved)}</td></>}{regular.map(e=><td key={e.id} className="px-3 py-2">{r.examValues[e.id]??'—'} / {e.maxMarks}</td>)}{combined.map(c=>{const x=r.combinedValues[c.id];return <td key={c.id} className="px-3 py-2">{x.combinedObtained}/{x.combinedMax} {x.combinedPercentage===null?'':`(${formatPercent(x.combinedPercentage,dec)})`}</td>})}<td className="px-3 py-2">{r.submitted}/{r.totalAssignments}</td><td className="px-3 py-2">{r.grace?formatNumber(r.grace,dec):'—'}</td></tr>)}</tbody></table></div></div></div>;
}
